---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: owasp-crs-demo
  labels:
    owasp: crs-podman
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: owasp-crs
  template:
    metadata:
      labels:
        app.kubernetes.io/name: owasp-crs
    spec:
      containers:
        - name: owaspcrsexample
          image: docker.io/owasp/modsecurity-crs:nginx-alpine
          ports:
            - containerPort: 80
              hostPort: 8080
              protocol: TCP
              name: crs-http
          env:
            - name: BACKEND
              value: http://127.0.0.1:5000
            - name: PARANOIA
              value: 5
        - name: philapp
          image: philflaskapp
          ports:
            - containerPort: 5000
              protocol: TCP
              name: flask-http
...
